use crate::models::entities::connection;
use crate::services::connection_service::ConnectionService;
use axum::{
    extract::{Path, State},
    http::StatusCode,
    response::IntoResponse,
    Json,
};
use sea_orm::DatabaseConnection;
use uuid::Uuid;

use chrono::Utc;
use serde::Deserialize;

#[derive(Deserialize)]
pub struct CreateConnectionRequest {
    pub name: String,
    #[serde(rename = "type")]
    pub db_type: String,
    pub host: String,
    pub port: i32,
    pub database: String,
    pub username: String,
    pub password: String,
    #[serde(default)]
    pub ssl: Option<bool>,
    pub ssl_cert: Option<String>,
}

// List all connections
pub async fn list_connections(State(db): State<DatabaseConnection>) -> impl IntoResponse {
    let service = ConnectionService::new(db).expect("Failed to create service");
    match service.get_all_connections().await {
        Ok(connections) => (StatusCode::OK, Json(connections)).into_response(),
        Err(e) => (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()).into_response(),
    }
}

// Get connection by ID
pub async fn get_connection(
    State(db): State<DatabaseConnection>,
    Path(id): Path<Uuid>,
) -> impl IntoResponse {
    let service = ConnectionService::new(db).expect("Failed to create service");
    match service.get_connection_by_id(id).await {
        Ok(Some(connection)) => (StatusCode::OK, Json(connection)).into_response(),
        Ok(None) => (StatusCode::NOT_FOUND, "Connection not found").into_response(),
        Err(e) => (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()).into_response(),
    }
}

// Create new connection
pub async fn create_connection(
    State(db): State<DatabaseConnection>,
    Json(payload): Json<CreateConnectionRequest>,
) -> impl IntoResponse {
    let service = ConnectionService::new(db).expect("Failed to create service");

    // Map DTO to Model (ID will be generated by service)
    let model = connection::Model {
        id: Uuid::new_v4(), // Placeholder, ignored by service
        name: payload.name,
        db_type: payload.db_type,
        host: payload.host,
        port: payload.port,
        database: payload.database,
        username: payload.username,
        password: payload.password,
        ssl: payload.ssl.unwrap_or(false),
        ssl_cert: payload.ssl_cert,
        last_used: None,
        created_at: Utc::now().into(),
        updated_at: Utc::now().into(),
    };

    match service.create_connection(model).await {
        Ok(connection) => (StatusCode::CREATED, Json(connection)).into_response(),
        Err(e) => (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()).into_response(),
    }
}

// Update connection
pub async fn update_connection(
    State(db): State<DatabaseConnection>,
    Path(id): Path<Uuid>,
    Json(payload): Json<CreateConnectionRequest>,
) -> impl IntoResponse {
    let service = ConnectionService::new(db).expect("Failed to create service");

    let model = connection::Model {
        id,
        name: payload.name,
        db_type: payload.db_type,
        host: payload.host,
        port: payload.port,
        database: payload.database,
        username: payload.username,
        password: payload.password,
        ssl: payload.ssl.unwrap_or(false),
        ssl_cert: payload.ssl_cert,
        last_used: None,
        created_at: Utc::now().into(),
        updated_at: Utc::now().into(),
    };

    match service.update_connection(id, model).await {
        Ok(connection) => (StatusCode::OK, Json(connection)).into_response(),
        Err(e) => (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()).into_response(),
    }
}

// Delete connection
pub async fn delete_connection(
    State(db): State<DatabaseConnection>,
    Path(id): Path<Uuid>,
) -> impl IntoResponse {
    let service = ConnectionService::new(db).expect("Failed to create service");
    match service.delete_connection(id).await {
        Ok(_) => (StatusCode::NO_CONTENT, ()).into_response(),
        Err(e) => (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()).into_response(),
    }
}

// Test connection
pub async fn test_connection(
    State(db): State<DatabaseConnection>,
    Json(payload): Json<CreateConnectionRequest>,
) -> impl IntoResponse {
    let service = ConnectionService::new(db).expect("Failed to create service");

    // Create a temporary model from request
    let model = connection::Model {
        id: Uuid::new_v4(),
        name: payload.name,
        db_type: payload.db_type,
        host: payload.host,
        port: payload.port,
        database: payload.database,
        username: payload.username,
        password: payload.password.clone(),
        ssl: payload.ssl.unwrap_or(false),
        ssl_cert: payload.ssl_cert,
        last_used: None,
        created_at: Utc::now().into(),
        updated_at: Utc::now().into(),
    };

    match service.test_connection(model, &payload.password).await {
        Ok(_) => (StatusCode::OK, "Connection successful").into_response(),
        Err(e) => (StatusCode::BAD_REQUEST, e.to_string()).into_response(),
    }
}
